### ISSUE TITLE
recordedFormatに<epsode:2>と桁揃えを指定すると、録画に失敗する

### ISSUE THREAD

**Issue by shirow-github** [kanreisa/Chinachu#151]
例えば
recordedFormat =  "<type><channel>-マッドメン　シーズン１_<episode:2>-<date:yyyymmdd_HHMM>.m2ts"
とした場合、
「BS141-マッドメン　シーズン１_08-20150224_2300.m2ts」と録画して欲しいのですが、
Operatorログ上には以下のエラーが出て全く録画が出来ません。

'-------------------------------------------------------------------
uncaughtException: ReferenceError: string is not defined
at /home/chinachu/chinachu/node_modules/chinachu-common/lib/chinachu-common.js:278:44
at String.replace (native)
at Object.exports.formatRecordedName (/home/chinachu/chinachu/node_modules/chinachu-common/lib/chinachu-common.js:237:14)
at doRecord (/home/chinachu/chinachu/app-operator.js:255:42)
at null._onTimeout (/home/chinachu/chinachu/app-operator.js:382:3)
at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
'-------------------------------------------------------------------

episodeの無い番組については、話数の代わりにnが表示されて通常通り録画出来ています。

**Comment by kanreisa** [comment]
1. service chinachu-operator stop
2. chinachu installer
 - 5
3. reboot

**Comment by shirow-github** [comment]
更新後、再起動したら無事に録画することが出来ました。
ありがとうございました。
