### ISSUE TITLE
EPG取得のときにエラーが起きます

### ISSUE THREAD

**Issue by mizikanamono** [kanreisa/Chinachu#256]
chinuchuセットアップは初めてでEPG取得時にエラーが発生し自力で色々調べましたが分からずこちらのほうで質問させてもらいました。
ubuntu server 14.04とPT3という環境です。
以下がEPG取得時の全ログです
```
4 Jan 05:18:01 - GETTING EPG.
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [0] {"type":"GR","channel":"27","n":0}
4 Jan 05:18:01 - [0] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [0] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 27 - - (pid=undefined)
4 Jan 05:18:01 - [0] STREAM: /tmp/chinachu-tmp-iiyzd1zu.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [1] {"type":"GR","channel":"26","n":1}
4 Jan 05:18:01 - [1] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [1] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 26 - - (pid=undefined)
4 Jan 05:18:01 - [1] STREAM: /tmp/chinachu-tmp-iiyzd204.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [2] {"type":"GR","channel":"25","n":2}
4 Jan 05:18:01 - [2] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [2] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 25 - - (pid=undefined)
4 Jan 05:18:01 - [2] STREAM: /tmp/chinachu-tmp-iiyzd209.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [3] {"type":"GR","channel":"24","n":3}
4 Jan 05:18:01 - [3] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [3] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 24 - - (pid=undefined)
4 Jan 05:18:01 - [3] STREAM: /tmp/chinachu-tmp-iiyzd20e.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [4] {"type":"GR","channel":"22","n":4}
4 Jan 05:18:01 - [4] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [4] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 22 - - (pid=undefined)
4 Jan 05:18:01 - [4] STREAM: /tmp/chinachu-tmp-iiyzd20i.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [5] {"type":"GR","channel":"23","n":5}
4 Jan 05:18:01 - [5] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [5] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 23 - - (pid=undefined)
4 Jan 05:18:01 - [5] STREAM: /tmp/chinachu-tmp-iiyzd20l.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [6] {"type":"GR","channel":"21","n":6}
4 Jan 05:18:01 - [6] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [6] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 21 - - (pid=undefined)
4 Jan 05:18:01 - [6] STREAM: /tmp/chinachu-tmp-iiyzd20p.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [7] {"type":"GR","channel":"16","n":7}
4 Jan 05:18:01 - [7] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [7] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 16 - - (pid=undefined)
4 Jan 05:18:01 - [7] STREAM: /tmp/chinachu-tmp-iiyzd20t.m2ts
/bin/sh: 1: kill: Illegal number: undefined
4 Jan 05:18:01 - [8] {"type":"GR","channel":"28","n":8}
4 Jan 05:18:01 - [8] LOCK: PT3-T1 (n=2)
4 Jan 05:18:01 - [8] SPAWN: recpt1 --device /dev/pt3video2 --sid epg 28 - - (pid=undefined)
4 Jan 05:18:01 - [8] STREAM: /tmp/chinachu-tmp-iiyzd20x.m2ts
4 Jan 05:18:01 - STATUS: { completed: 0, waiting: 9, worked: 9, running: 9 }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn recpt1 ENOENT
    at exports._errnoException (util.js:849:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3
failed somehow
```
以下がconfig.jsonの"tuners"です
```
{
      "name"        : "PT3-S1",
      "isScrambling": false,
      "types"       : [ "BS", "CS" ],
      "command"     : "recpt1 --device /dev/pt3video0 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT3-S2",
      "isScrambling": false,
      "types"       : [ "BS", "CS" ],
      "command"     : "recpt1 --device /dev/pt3video1 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT3-T1",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recpt1 --device /dev/pt3video2 --b25 --strip --sid <sid> <channel> - -"
    },
    {
      "name"        : "PT3-T2",
      "isScrambling": false,
      "types"       : [ "GR" ],
      "command"     : "recpt1 --device /dev/pt3video3 --b25 --strip --sid <sid> <channel> - -"
    }
  ],
```
config.jsonの "channels"を空にし取得してみた所、エラーは起きなかったです。
ubuntu serverでPT3とカードリーダー、どちらも正常に認識されてました。
長文ですみません。アドバイスよろしくお願いします。

**Comment by kanreisa** [comment]
**Error: spawn recpt1 ENOENT** ここにエラーのすべてが書かれています

**Comment by mizikanamono** [comment]
回答ありがとうございます。
それは分かるんですが・・・・エラーの意味が分からずで・・・
初心者ですみません

**Comment by kanreisa** [comment]
`recpt1` というコマンドにパスが通ってないか、入ってないか、見えないかとかだと思います。
これで解決しなければ Slack で質問してみていただけると幸いです

**Comment by mizikanamono** [comment]
recpt1がインストールされてないことが原因でした・・・
回答ありがとうございました
